#!/usr/bin/env python3
"""
Generate 10 score dial bitmaps (scores 1-10) for the Arduino thermal printer sketch.
Output: arduino/speculative_ai/bitmaps.h

Run:  python generate_bitmaps.py
Requires: pip install Pillow
"""
import os
import math

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError:
    print("ERROR: Pillow not installed. Run: pip install Pillow")
    raise

# ── Dial geometry ─────────────────────────────────────────────────────────────
# Full-width bitmap (384px = 58mm paper at 203 dpi) with dial centered
BITMAP_W    = 384   # output bitmap width  (must be divisible by 8)
BITMAP_H    = 256   # output bitmap height
CX          = BITMAP_W // 2   # 192
CY          = BITMAP_H // 2   # 128
R           = 110   # arc radius (diameter ≈ 220px)
STROKE_BG   = 2     # background arc width
STROKE_FILL = 7     # filled arc width

# Arc spans 240° starting from PIL angle 150° (lower-left, same feel as SVG dial)
GAUGE_START = 150
GAUGE_SWEEP = 240

# ── Font search ───────────────────────────────────────────────────────────────
FONT_CANDIDATES = [
    "DejaVuSansMono-Bold.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf",
    "/System/Library/Fonts/Courier.ttc",
    "/System/Library/Fonts/Monaco.ttf",
    "Courier New Bold.ttf",
    "cour.ttf",
]

def _load_font(size):
    for path in FONT_CANDIDATES:
        try:
            return ImageFont.truetype(path, size)
        except (IOError, OSError):
            continue
    return ImageFont.load_default()


def make_dial(score: int) -> Image.Image:
    """Draw a BITMAP_W×BITMAP_H 1-bit gauge dial for the given score (1–10)."""
    img  = Image.new("1", (BITMAP_W, BITMAP_H), 1)   # 1 = white background
    draw = ImageDraw.Draw(img)
    box  = [CX - R, CY - R, CX + R, CY + R]

    # Background arc (full sweep, thin)
    draw.arc(box, GAUGE_START, GAUGE_START + GAUGE_SWEEP, fill=0, width=STROKE_BG)

    # Filled arc (score proportion)
    if score > 0:
        fill_end = GAUGE_START + (score / 10) * GAUGE_SWEEP
        draw.arc(box, GAUGE_START, fill_end, fill=0, width=STROKE_FILL)

    # Score number centred
    font = _load_font(32)
    text = str(score)
    bb   = draw.textbbox((0, 0), text, font=font)
    tw, th = bb[2] - bb[0], bb[3] - bb[1]
    draw.text((CX - tw // 2, CY - th // 2 - 2), text, fill=0, font=font)

    return img


def img_to_bytes(img: Image.Image) -> list:
    """Convert 1-bit PIL image → row-major byte list (MSB first, 0=black in mode '1')."""
    w, h      = img.size
    row_bytes = (w + 7) // 8
    data      = []
    for y in range(h):
        for bx in range(row_bytes):
            byte = 0
            for bit in range(8):
                x = bx * 8 + bit
                if x < w and img.getpixel((x, y)) == 0:   # 0 = black in mode "1"
                    byte |= (0x80 >> bit)
            data.append(byte)
    return data


def main():
    out_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                           "arduino", "speculative_ai")
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "bitmaps.h")

    row_bytes   = BITMAP_W // 8          # 48 (BITMAP_W is guaranteed divisible by 8)
    total_bytes = BITMAP_H * row_bytes   # 256 × 48 = 12288

    print(f"Generating {BITMAP_W}×{BITMAP_H} bitmaps for scores 1–10 …")

    with open(out_path, "w") as f:
        f.write("// Auto-generated by generate_bitmaps.py — do not edit by hand.\n")
        f.write("// Run: python generate_bitmaps.py\n")
        f.write("// v1 — 384×256 dials, centred on full paper width\n\n")
        f.write("#pragma once\n")
        f.write("#include <avr/pgmspace.h>\n\n")
        f.write(f"#define DIAL_W     {BITMAP_W}\n")
        f.write(f"#define DIAL_H     {BITMAP_H}\n")
        f.write(f"#define DIAL_BYTES {total_bytes}\n\n")

        for s in range(1, 11):
            img  = make_dial(s)
            data = img_to_bytes(img)
            assert len(data) == total_bytes, f"Unexpected byte count for score {s}"

            f.write(f"const uint8_t score_{s}[DIAL_BYTES] PROGMEM = {{\n")
            # 16 bytes per line for readability
            for i in range(0, len(data), 16):
                chunk = data[i:i+16]
                f.write("  " + ", ".join(f"0x{b:02X}" for b in chunk) + ",\n")
            f.write("};\n\n")
            print(f"  score_{s}: {len(data)} bytes")

    print(f"\nWrote {out_path}")
    print("Now recompile and upload arduino/speculative_ai/speculative_ai.ino")


if __name__ == "__main__":
    main()
